##please be sure of what you are doing before editing !!

version: '3.8'
services:
  bedrock:
    image: itzg/minecraft-bedrock-server
    container_name: mc-bedrock
    environment:
      # Core Settings
      EULA: ${EULA:-"FALSE"}
      VERSION: ${VERSION}
      PACKAGE_BACKUP_KEEP: ${PACKAGE_BACKUP_KEEP}
      
      # Server Properties
      SERVER_NAME: ${SERVER_NAME}
      SERVER_PORT: ${SERVER_PORT:-19132}
      SERVER_PORT_V6: ${SERVER_PORT_V6:-19133}
      GAMEMODE: ${GAMEMODE}
      DIFFICULTY: ${DIFFICULTY}
      LEVEL_TYPE: ${LEVEL_TYPE}
      ALLOW_CHEATS: ${ALLOW_CHEATS}
      MAX_PLAYERS: ${MAX_PLAYERS}
      ONLINE_MODE: ${ONLINE_MODE}
      WHITE_LIST: ${WHITE_LIST}
      VIEW_DISTANCE: ${VIEW_DISTANCE}
      TICK_DISTANCE: ${TICK_DISTANCE}
      PLAYER_IDLE_TIMEOUT: ${PLAYER_IDLE_TIMEOUT}
      MAX_THREADS: ${MAX_THREADS}
      LEVEL_NAME: ${LEVEL_NAME}
      LEVEL_SEED: ${LEVEL_SEED}
      DEFAULT_PLAYER_PERMISSION_LEVEL: ${DEFAULT_PLAYER_PERMISSION_LEVEL}
      TEXTUREPACK_REQUIRED: ${TEXTUREPACK_REQUIRED}
      
      # Movement Settings
      SERVER_AUTHORITATIVE_MOVEMENT: ${SERVER_AUTHORITATIVE_MOVEMENT}
      PLAYER_MOVEMENT_SCORE_THRESHOLD: ${PLAYER_MOVEMENT_SCORE_THRESHOLD}
      PLAYER_MOVEMENT_DISTANCE_THRESHOLD: ${PLAYER_MOVEMENT_DISTANCE_THRESHOLD}
      PLAYER_MOVEMENT_DURATION_THRESHOLD_IN_MS: ${PLAYER_MOVEMENT_DURATION_THRESHOLD_IN_MS}
      CORRECT_PLAYER_MOVEMENT: ${CORRECT_PLAYER_MOVEMENT}
    
    ports:
      - "${SERVER_PORT:-19132}:${SERVER_PORT:-19132}/udp"
      - "${SERVER_PORT_V6:-19133}:${SERVER_PORT_V6:-19133}/udp"
    
    volumes:
      - ${MINECRAFT_DATA_DIR:-./minecraft-data}:/data
    
    restart: unless-stopped
    stdin_open: true
    tty: true